name: RedTeamDesign
description: "Articles on front-end development, CSS, HTML, JavaScript and more."
markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
excerpt_separator: <!-- more -->
exclude: [rtd.sublime-project, rtd.sublime-workspace, CNAME, Gruntfile.js, package.json, README.md]
abs_url: http://www.red-team-design.com
future: false